### ISSUE TITLE
Trouble binding to certain IP's and ports

### ISSUE THREAD

**Issue by EganJ** [Voltron-UTD/LidarInterface#1]
As of 5720a398abe03b34bb176082a5074ecd1c8f1ee5, the velodyne node for the rear node (the one with a changed IP) cannot launch because it cannot bind to the ip.

**Comment by wheitman** [comment]
Are you running this within VDE? If so, you'll likely need to edit VDE's docker-compose.yml to forward the IP to the base service. You'll see some ports are forwarded already, so I think it's a similar process...

**Comment by EganJ** [comment]
Sounds good. I'll look into that. 

Here's the error message if it ever becomes relevant:
```
[velodyne_cloud_node_exe-2] bind: Cannot assign requested address
[ERROR] [velodyne_cloud_node_exe-2]: process has died [pid 1350, exit code 2, cmd '/opt/AutowareAuto/install/velodyne_nodes/lib/velodyne_nodes/velodyne_cloud_node_exe --model vlp16 --ros-args -r __ns:=/lidar_rear --params-file /home/docker/LidarInterface/install/voltron_lidar_stack/share/voltron_lidar_stack/param/vlp16_voltron_rear.param.yaml -r topic:=points_raw']```

**Comment by EganJ** [comment]
Did some poking around and wrapped my head around the issue a bit more. It looks like we get to choose the IP it publishes to, but I don't know enough about networking to know if there are any constraints on which IP addresses we can choose. I think the current defaults (255.255.255.255 and 192.168.1.201) might have some funny business around them that is causing the issue. I do know that with a different IP the data can be read in Wireshark, but I haven't tested it on the defaults.

(The reason I was using wireshark happened to be I lost the IP address by accidentially enabling DHCP, which turns out to not be the move since with the randomized IP you can't turn it back off until you've found it again.)

**Comment by EganJ** [comment]
With dcf81cf, both front and rear nodes are simultaneously receiving data from the broadcast IP. Haven't plotted the output but listening to all nodes with `ros2 topic echo` has output all the way through point fusion, so this should be fine.
